export const wilayas = [
  {
    code: "01",
    name: "Adrar",
    ar_name: "أدرار",
    region: "Sud",
    capital: "Adrar",
    codePostal: "01000",
  },
  {
    code: "02",
    name: "Chlef",
    ar_name: "الشلف",
    region: "Nord",
    capital: "Chlef",
    codePostal: "02000",
  },
  {
    code: "03",
    name: "Laghouat",
    ar_name: "الأغواط",
    region: "Sud",
    capital: "Laghouat",
    codePostal: "03000",
  },
  {
    code: "04",
    name: "Oum El Bouaghi",
    ar_name: "أم البواقي",
    region: "Est",
    capital: "Oum El Bouaghi",
    codePostal: "04000",
  },
  {
    code: "05",
    name: "Batna",
    ar_name: "باتنة",
    region: "Est",
    capital: "Batna",
    codePostal: "05000",
  },
  {
    code: "06",
    name: "Béjaïa",
    ar_name: "بجاية",
    region: "Nord",
    capital: "Béjaïa",
    codePostal: "06000",
  },
  {
    code: "07",
    name: "Biskra",
    ar_name: "بسكرة",
    region: "Est",
    capital: "Biskra",
    codePostal: "07000",
  },
  {
    code: "08",
    name: "Béchar",
    ar_name: "بشار",
    region: "Sud",
    capital: "Béchar",
    codePostal: "08000",
  },
  {
    code: "09",
    name: "Blida",
    ar_name: "البليدة",
    region: "Nord",
    capital: "Blida",
    codePostal: "09000",
  },
  {
    code: "10",
    name: "Bouira",
    ar_name: "البويرة",
    region: "Nord",
    capital: "Bouira",
    codePostal: "10000",
  },
  {
    code: "11",
    name: "Tamanrasset",
    ar_name: "تمنراست",
    region: "Sud",
    capital: "Tamanrasset",
    codePostal: "11000",
  },
  {
    code: "12",
    name: "Tébessa",
    ar_name: "تبسة",
    region: "Est",
    capital: "Tébessa",
    codePostal: "12000",
  },
  {
    code: "13",
    name: "Tlemcen",
    ar_name: "تلمسان",
    region: "Nord-Ouest",
    capital: "Tlemcen",
    codePostal: "13000",
  },
  {
    code: "14",
    name: "Tiaret",
    ar_name: "تيارت",
    region: "Centre",
    capital: "Tiaret",
    codePostal: "14000",
  },
  {
    code: "15",
    name: "Tizi Ouzou",
    ar_name: "تيزي وزو",
    region: "Nord",
    capital: "Tizi Ouzou",
    codePostal: "15000",
  },
  {
    code: "16",
    name: "Alger",
    ar_name: "الجزائر",
    region: "Nord",
    capital: "Alger",
    codePostal: "16000",
  },
  {
    code: "17",
    name: "Djelfa",
    ar_name: "الجلفة",
    region: "Centre-Sud",
    capital: "Djelfa",
    codePostal: "17000",
  },
  {
    code: "18",
    name: "Jijel",
    ar_name: "جيجل",
    region: "Nord-Est",
    capital: "Jijel",
    codePostal: "18000",
  },
  {
    code: "19",
    name: "Sétif",
    ar_name: "سطيف",
    region: "Est-Centre",
    capital: "Sétif",
    codePostal: "19000",
  },
  {
    code: "20",
    name: "Saïda",
    ar_name: "سعيدة",
    region: "Ouest-Centre",
    capital: "Saïda",
    codePostal: "20000",
  },
  {
    code: "21",
    name: "Skikda",
    ar_name: "سكيكدة",
    region: "Nord-Est",
    capital: "Skikda",
    codePostal: "21000",
  },
  {
    code: "22",
    name: "Sidi Bel Abbès",
    ar_name: "سيدي بلعباس",
    region: "Ouest",
    capital: "Sidi Bel Abbès",
    codePostal: "22000",
  },
  {
    code: "23",
    name: "Annaba",
    ar_name: "عنابة",
    region: "Nord-Est",
    capital: "Annaba",
    codePostal: "23000",
  },
  {
    code: "24",
    name: "Guelma",
    ar_name: "قالمة",
    region: "Est",
    capital: "Guelma",
    codePostal: "24000",
  },
  {
    code: "25",
    name: "Constantine",
    ar_name: "قسنطينة",
    region: "Est",
    capital: "Constantine",
    codePostal: "25000",
  },
  {
    code: "26",
    name: "Médéa",
    ar_name: "المدية",
    region: "Centre",
    capital: "Médéa",
    codePostal: "26000",
  },
  {
    code: "27",
    name: "Mostaganem",
    ar_name: "مستغانم",
    region: "Ouest",
    capital: "Mostaganem",
    codePostal: "27000",
  },
  {
    code: "28",
    name: "M'Sila",
    ar_name: "المسيلة",
    region: "Centre",
    capital: "M'Sila",
    codePostal: "28000",
  },
  {
    code: "29",
    name: "Mascara",
    ar_name: "معسكر",
    region: "Ouest",
    capital: "Mascara",
    codePostal: "29000",
  },
  {
    code: "30",
    name: "Ouargla",
    ar_name: "ورقلة",
    region: "Sud",
    capital: "Ouargla",
    codePostal: "30000",
  },
  {
    code: "31",
    name: "Oran",
    ar_name: "وهران",
    region: "Ouest",
    capital: "Oran",
    codePostal: "31000",
  },
  {
    code: "32",
    name: "El Bayadh",
    ar_name: "البيض",
    region: "Sud-Ouest",
    capital: "El Bayadh",
    codePostal: "32000",
  },
  {
    code: "33",
    name: "Illizi",
    ar_name: "إليزي",
    region: "Sud-Est",
    capital: "Illizi",
    codePostal: "33000",
  },
  {
    code: "34",
    name: "Bordj Bou Arreridj",
    ar_name: "برج بوعريريج",
    region: "Est",
    capital: "Bordj Bou Arreridj",
    codePostal: "34000",
  },
  {
    code: "35",
    name: "Boumerdès",
    ar_name: "بومرداس",
    region: "Nord",
    capital: "Boumerdès",
    codePostal: "35000",
  },
  {
    code: "36",
    name: "El Tarf",
    ar_name: "الطارف",
    region: "Est",
    capital: "El Tarf",
    codePostal: "36000",
  },
  {
    code: "37",
    name: "Tindouf",
    ar_name: "تندوف",
    region: "Sud-Ouest",
    capital: "Tindouf",
    codePostal: "37000",
  },
  {
    code: "38",
    name: "Tissemsilt",
    ar_name: "تيسمسيلت",
    region: "Centre",
    capital: "Tissemsilt",
    codePostal: "38000",
  },
  {
    code: "39",
    name: "El Oued",
    ar_name: "الوادي",
    region: "Sud-Est",
    capital: "El Oued",
    codePostal: "39000",
  },
  {
    code: "40",
    name: "Khenchela",
    ar_name: "خنشلة",
    region: "Est",
    capital: "Khenchela",
    codePostal: "40000",
  },
  {
    code: "41",
    name: "Souk Ahras",
    ar_name: "سوق أهراس",
    region: "Est",
    capital: "Souk Ahras",
    codePostal: "41000",
  },
  {
    code: "42",
    name: "Tipaza",
    ar_name: "تيبازة",
    region: "Nord",
    capital: "Tipaza",
    codePostal: "42000",
  },
  {
    code: "43",
    name: "Mila",
    ar_name: "ميلة",
    region: "Est",
    capital: "Mila",
    codePostal: "43000",
  },
  {
    code: "44",
    name: "Aïn Defla",
    ar_name: "عين الدفلى",
    region: "Centre",
    capital: "Aïn Defla",
    codePostal: "44000",
  },
  {
    code: "45",
    name: "Naâma",
    ar_name: "النعامة",
    region: "Sud-Ouest",
    capital: "Naâma",
    codePostal: "45000",
  },
  {
    code: "46",
    name: "Aïn Témouchent",
    ar_name: "عين تموشنت",
    region: "Ouest",
    capital: "Aïn Témouchent",
    codePostal: "46000",
  },
  {
    code: "47",
    name: "Ghardaïa",
    ar_name: "غرداية",
    region: "Sud",
    capital: "Ghardaïa",
    codePostal: "47000",
  },
  {
    code: "48",
    name: "Relizane",
    ar_name: "غليزان",
    region: "Ouest",
    capital: "Relizane",
    codePostal: "48000",
  },
  {
    code: "49",
    name: "Timimoun",
    ar_name: "تيميمون",
    region: "Sud",
    capital: "Timimoun",
    codePostal: "49000",
  },
  {
    code: "50",
    name: "Bordj Badji Mokhtar",
    ar_name: "برج باجي مختار",
    region: "Sud",
    capital: "Bordj Badji Mokhtar",
    codePostal: "50000",
  },
  {
    code: "51",
    name: "Ouled Djellal",
    ar_name: "أولاد جلال",
    region: "Sud",
    capital: "Ouled Djellal",
    codePostal: "51000",
  },
  {
    code: "52",
    name: "Béni Abbès",
    ar_name: "بني عباس",
    region: "Sud",
    capital: "Béni Abbès",
    codePostal: "52000",
  },
  {
    code: "53",
    name: "In Salah",
    ar_name: "عين صالح",
    region: "Sud",
    capital: "In Salah",
    codePostal: "53000",
  },
  {
    code: "54",
    name: "In Guezzam",
    ar_name: "عين قزام",
    region: "Sud",
    capital: "In Guezzam",
    codePostal: "54000",
  },
  {
    code: "55",
    name: "Touggourt",
    ar_name: "تقرت",
    region: "Sud-Est",
    capital: "Touggourt",
    codePostal: "55000",
  },
  {
    code: "56",
    name: "Djanet",
    ar_name: "جانت",
    region: "Sud-Est",
    capital: "Djanet",
    codePostal: "56000",
  },
  {
    code: "57",
    name: "El M'Ghair",
    ar_name: "المغير",
    region: "Sud-Est",
    capital: "El M'Ghair",
    codePostal: "57000",
  },
  {
    code: "58",
    name: "El Meniaa",
    ar_name: "المنيعة",
    region: "Sud",
    capital: "El Meniaa",
    codePostal: "58000",
  },
];
